resource_group_name = "Devops"
admin_password      = "Winner007!"
admin_username      = "adminuser"
size                = "Standard_D2s_v3"
sku                 = "18.04-LTS"
storage_account_type= "Standard_LRS"