name: Terraform Plan

on:
  push:
    branches:
      - main
    pull_request:

permissions:
      id-token: write
      contents: read
jobs:
  terraform:
    name: 'Terraform'
    # env:
    #   ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
    #   ARM_CLIENT_SCRETE: ${{secrets.CLIENT_SECRET}}
    #   ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
    #   ARM_TENENT_ID: ${{secrets.TENANT_ID}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install jq -y
      
      - name: Parse JSON
        run: chmod +x sample.sh | ./sample.sh
        id: shell_script
      
      # - name: Set Outputs
      #   run: |
      #     OUTPUT=$(./sample.sh)
      #     echo "$OUTPUT"

      # - name: Set Environment Variables
      #   run: |
      #     echo "$OUTPUT" | while read -r line; do
      #       eval "$line"
      #     done
      # - name: Use Shell Script Output
      #   run: |
      #     echo "The output is: ${{ env.my_output }}"

      - name: 'Az CLI login'
        # run: az login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        run: terraform -chdir=./config init
      
      - name: Terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
          resource_group_name: 
          admin_password:
          admin_username:
          size:
          sku:
          storage_account_type: 
        # run: terraform -chdir=config plan -var="resource_group_name=${{ vars.RESOURCE_GROUP_NAME }}" -var="admin_password=${{ vars.ADMIN_PASSWORD }}" -var="admin_username=${{ vars.ADMIN_USERNAME }}" -var="size=${{ vars.SIZE }}" -var="sku=${{ vars.SKU }}" -var="storage_account_type=${{ vars.STORAGE_ACCOUNT_TYPE }}"
        run: terraform -chdir=config plan -var="resource_group_name=${{ env.resource_group_name }}" -var="admin_password=${{ env.admin_password }}" -var="admin_username=${{ env.admin_username }}" -var="size=${{ env.size }}" -var="sku=${{ env.sku }}" -var="storage_account_type=${{ env.storage_account_type }}"



        
